services:
  mock-server:
    container_name: mock_server
    hostname: mock_server
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3002"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon/configuration.json:/data
    ports:
      - "3002:3002"